version: "2.2"
services:
  web:
    image: httpd:alpine
    ports:
      - 80:80
    volumes:
      - ${PWD}/web:/usr/local/apache2/htdocs
    depends_on:
      - bangserver
  bangserver:
    build: https://github.com/salvoilmiosi/banggameserver.git
    ports:
      - 47654:47654